name: Build and publish to public ECR

on:
  push:
    branches:
      - main
jobs:
  build:
    name: Publish image
    runs-on: ubuntu-latest
    steps:
      - name: Build and push to ECR
        uses: citizensadvice/build-and-push-action@v1
        with:
          aws_access_key: ${{ secrets.PUBLIC_PUSH_ECR_AWS_KEY }}
          aws_secret_key: ${{ secrets.PUBLIC_PUSH_ECR_AWS_SECRET }}
          dockerfile_context: '.'
          repository_name: github-actions-runner
          auth_token: ${{ secrets.GITHUB_TOKEN }}
